name: booru_app
description: App for yande and konachan

version: 0.1.6+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  dio: ^3.0.8
  shared_preferences: ">=0.5.8 <2.0.0"
  rxdart: ^0.23.1
  sqflite: ^1.1.7+1
  esys_flutter_share: ^1.0.2
  floating_search_bar: ^0.2.0
  photo_view: ^0.9.1
  sliding_up_panel: ^1.0.0
  devicelocale: ^0.2.1
  pull_to_refresh: ^1.5.8
  enum_to_string: ^1.0.8
  expandable: ^4.1.2
  cached_network_image: ^2.0.0
  path_provider:
  open_file: ^3.0.1
  crypto: ^2.1.3 # Sha1
  # Notification usage
  flutter_local_notifications: ^1.1.3
  overlay_support: ^1.0.2
  # Transition
  flutter_page_transition: ^0.1.6
  animated_stream_list: ^1.1.0
  # File path combiner
  path: ^1.6.4
  # Use the navigation bar as a switcher
  flutter_snake_navigationbar: ^0.3.0
  filesystem_picker: ^1.0.2
  uni_links: ^0.4.0
  auto_route: ^0.6.7
  animated_splash: ^1.0.0
  # flutter_native_splash: ^0.1.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher: ^5.5.0
  url_launcher_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/flutter_plugins/url_launcher_fde

# flutter pub pub run flutter_native_splash:create
# flutter_native_splash:
#   color: "e91e63"

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
    
  auto_route_generator: ^0.6.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - resources/images/app_icon.png